In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2.0,3.3], [4,5,6.5]])
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a1.shape

(3,)

In [17]:
a2.shape

(2, 3)

In [18]:
a3.shape

(2, 3, 3)

In [19]:
a1.ndim, a2.ndim ,a3.ndim

(1, 2, 3)

In [20]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [21]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [22]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# create a dataFrame from a NumPy array

In [25]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Numpy Array

In [26]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [27]:
sample_array.dtype

dtype('int32')

In [30]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
ones.dtype

dtype('float64')

In [32]:
type(ones)

numpy.ndarray

In [33]:
zeros = np.zeros((2,3))
zerosros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0,10, size = (3,5))
random_array

array([[8, 9, 5, 7, 7],
       [6, 8, 1, 9, 1],
       [6, 0, 5, 1, 2]])

In [37]:
random_array.size

15

In [38]:
random_array.shape

(3, 5)

In [42]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.02323104, 0.5946579 , 0.19611165],
       [0.16728999, 0.79376864, 0.12096516],
       [0.29016083, 0.83770576, 0.10337904],
       [0.95125086, 0.31571475, 0.15573165],
       [0.31591509, 0.79366987, 0.47610927]])

In [43]:
random_array_2.shape

(5, 3)

In [44]:
random_array_2.size

15

In [51]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.92256349, 0.01041274, 0.15346477],
       [0.19957269, 0.22566305, 0.36625926],
       [0.89212795, 0.8540605 , 0.4767507 ],
       [0.13835323, 0.00965661, 0.75315618],
       [0.37264419, 0.0769039 , 0.7725098 ]])

In [65]:
# pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size =(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [64]:
random_array_4.shape

(5, 3)

In [69]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [70]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])