In [1]:
import numpy as np
import pandas as pd

In [3]:
# load the data
# important node: this is where we will usually put data files
df = pd.read_csv('datasets/airfoil_self_noise.dat', sep='\t', header=None)

In [4]:
# check the data
df.head()
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1503 entries, 0 to 1502
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1503 non-null   int64  
 1   1       1503 non-null   float64
 2   2       1503 non-null   float64
 3   3       1503 non-null   float64
 4   4       1503 non-null   float64
 5   5       1503 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 70.6 KB


In [5]:
# get the inputs
data = df[[0,1,2,3,4]].values

In [6]:
data

array([[8.00000e+02, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.00000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [1.25000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       ...,
       [4.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [5.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [6.30000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02]])

In [7]:
target = df[5].values

In [8]:
target

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size = 0.33)

In [12]:
# instantiate a classifier and train it
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
# evaluate the model's performance
model.score(X_train, y_train)


0.5078969477017647

In [17]:
model.score(X_test, y_test)

0.5266168547055666

In [18]:
predictions = model.predict(X_test)
predictions

array([126.74085565, 131.86462125, 128.91694654, 122.29673555,
       118.84301355, 116.1381066 , 126.32435912, 126.74066382,
       126.5794213 , 128.24184926, 118.67306615, 117.81271795,
       115.50087685, 118.27593672, 126.65042701, 125.32192662,
       121.08559232, 126.15948148, 122.93047544, 127.12125467,
       124.08283638, 127.20325759, 121.62845805, 123.8600919 ,
       126.95966523, 123.53268871, 119.07175465, 127.62824658,
       124.63850576, 120.06935969, 125.37401   , 122.4419659 ,
       129.3332992 , 128.64188347, 132.04509781, 126.16552196,
       120.24863643, 118.52447953, 134.80813622, 123.11647662,
       125.77326613, 128.53336961, 122.20651908, 133.71946125,
       131.87188949, 126.79489286, 118.86308631, 122.30776347,
       129.58868219, 131.05028688, 127.58782255, 130.11180179,
       122.69034339, 129.02247433, 125.9522954 , 120.70070658,
       124.09894735, 123.00721334, 117.99439684, 126.44789218,
       124.51671871, 129.88449928, 122.94659968, 125.21

In [21]:
# we can even use random forest to solve the same problem
from sklearn.ensemble import RandomForestRegressor


In [24]:

model2 = RandomForestRegressor()
model2.fit(X_train, y_train)



RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [25]:
# evaluate model' performance
model2.score(X_train, y_train)

0.9892125102586735

In [26]:
model2.score(X_test, y_test)

0.9305281678271043